### ISSUE TITLE
Operator does not start: panic: too many open files

### ISSUE THREAD

**Issue by c-thiel** [authzed/spicedb-operator#150]
Dear spicedb Team,

I just deployed the operator using `kubectl apply --server-side -f https://github.com/authzed/spicedb-operator/releases/latest/download/bundle.yaml` and got `ghcr.io/authzed/spicedb-operator:v1.1.2` of the operator pod.

However the pod itself doesn't start and ends in a Crashloopbackoff with the following error in the logs:
```
I0214 20:53:33.589283       1 merged_client_builder.go:121] Using in-cluster configuration
panic: too many open files

goroutine 1 [running]:
github.com/authzed/controller-idioms/fileinformer.(*Factory).ForResource(0xc000187ce0, {{0x21445a0, 0xb}, {0x2136db9, 0x2}, {0x7ffda3b0edfb, 0x19}})
	/home/runner/go/pkg/mod/github.com/authzed/controller-idioms@v0.7.0/fileinformer/file_informer.go:74 +0x3b5
github.com/authzed/spicedb-operator/pkg/controller.NewController({0x2498b50, 0xc0000e9d80}, 0xc0006a5b10?, {0x247b660, 0xc000430490}, {0x24bd3f0, 0xc00048a680}, {0x7ffda3b0edfb, 0x19}, {0x249edf0, ...})
	/home/runner/work/spicedb-operator/spicedb-operator/pkg/controller/controller.go:111 +0x393
github.com/authzed/spicedb-operator/pkg/cmd/run.(*Options).Run(0xc00070caa0, {0x2498b50, 0xc0000e9d80}, {0x24a9d80?, 0xc0000e9ac0?})
	/home/runner/work/spicedb-operator/spicedb-operator/pkg/cmd/run/run.go:143 +0x645
github.com/authzed/spicedb-operator/pkg/cmd/run.NewCmdRun.func1(0xc0005a3500?, {0x2137e47?, 0x4?, 0x4?})
	/home/runner/work/spicedb-operator/spicedb-operator/pkg/cmd/run/run.go:67 +0x8a
github.com/spf13/cobra.(*Command).execute(0xc0005a3500, {0xc0000e9d00, 0x4, 0x4})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc0005a3200)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:1040 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:968
main.main()
	/home/runner/work/spicedb-operator/spicedb-operator/cmd/spicedb-operator/main.go:33 +0x299
```

Any idea where this is comming from? 

I am running on v1.23.6+rke2r2.

**Comment by ecordell** [comment]
> I am running on v1.23.6+rke2r2

I'm guessing RKE imposes a limit on file descriptors that the operator is hitting. I see a related issue https://github.com/rancher/rke2/issues/2382 - can you try some of those steps and see if that's it? 

Can you try in another flavor of kube, or is RKE a requirement for you?

**Comment by c-thiel** [comment]
You are right - other pods start failing as well. Not an issue here. Thanks :)
Closing it now.
